/*
 * Anchore Enterprise Feeds
 *
 * Enterprise service for normalizing vulnerability data from external sources and making it available via API
 *
 * API version: 0.0.1
 * Contact: dev@anchore.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ServiceVersionDb struct for ServiceVersionDb
type ServiceVersionDb struct {
	// Semantic version of the db schema
	SchemaVersion string `json:"schema_version,omitempty"`
}
