/*
 * Anchore Enterprise Feeds
 *
 * Enterprise service for normalizing vulnerability data from external sources and making it available via API
 *
 * API version: 0.0.1
 * Contact: dev@anchore.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ServiceVersionApi Api Version string
type ServiceVersionApi struct {
	// Semantic version of the api
	Version string `json:"version,omitempty"`
}
