/*
 * Anchore Enterprise Feeds
 *
 * Enterprise service for normalizing vulnerability data from external sources and making it available via API
 *
 * API version: 0.0.1
 * Contact: dev@anchore.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Task A unit of work triggered either by the system or the user
type Task struct {
	TaskId int32 `json:"task_id,omitempty"`
	TaskType string `json:"task_type,omitempty"`
	FeedId string `json:"feed_id,omitempty"`
	DriverId string `json:"driver_id,omitempty"`
	Status string `json:"status,omitempty"`
	Result map[string]interface{} `json:"result,omitempty"`
	StartTime string `json:"start_time,omitempty"`
	EndTime string `json:"end_time,omitempty"`
	StartedBy string `json:"started_by,omitempty"`
	ParentTaskId int32 `json:"parent_task_id,omitempty"`
	SubTasks []Task `json:"sub_tasks,omitempty"`
}
